[package]
name = "movies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk={version='0.6.1', package='gtk4'}
walkdir='2.3.2'
regex='1.7.1'
libadwaita='0.3.1'
# reqwest='0.11.14'
